function [observed_data] = run_model(fault_type, fault_time)
%   function [ observed_data, isFault ] = run_model(fault_type, fault_time)
%  
%   fault_type -- type of fault:
%       0 -- without fault
%       1 -- valve_car_tank_soft_fault
%       2 -- valve_car_tank_hard_fault
%       3 -- valve_minipump_in_soft_fault
%       4 -- valve_minipump_in_hard_fault
%       5 -- valve_minipump_out_soft_fault
%       6 -- valve_minipump_out_hard_fault
%       7 -- valve_tank1_in_soft_fault
%       8 -- valve_tank1_in_hard_fault
%       9 -- valve_tank1_out_soft_fault
%       10 -- valve_tank1_out_hard_fault
%       11 -- valve_tank2_in_soft_fault
%       12 -- valve_tank2_in_hard_fault
%       13 -- valve_tank2_out_soft_fault
%       14 -- valve_tank2_out_hard_fault
%       15 -- valve_tank3_in_soft_fault
%       16 -- valve_tank3_in_hard_fault
%       17 -- valve_tank3_out_soft_fault
%       18 -- valve_tank3_out_hard_fault
%       19 -- valve_bigpump_in_soft_fault
%       20 -- valve_bigpump_in_hard_fault
%       21 -- valve_bigpump_out_soft_fault
%       22 -- valve_bigpump_out_hard_fault
%       23 -- valve_general_tank_soft_fault
%       24 -- valve_general_tank_hard_fault
%       25 -- filter_soft_fault
%       26 -- filter_hard_fault
%       27 -- minipump_soft_fault
%       28 -- minipump_hard_fault
%       29 -- bigpump_soft_fault
%       30 -- bigpump_hard_fault



    
    ws_fault_time = fault_time;
    assignin('base', 'ws_fault_time', ws_fault_time);
    frequency=0.01;
    assignin('base', 'frequency', frequency);
    time_const=700;
    assignin('base', 'time_const', time_const);
    hard=3/2;
    assignin('base', 'hard', hard);
    soft=1/2;
    assignin('base', 'soft', soft);
    
    switch (fault_type)
        case 0  %       0 -- without fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=0;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 1  %       1 -- valve_car_tank_soft_fault
                ws_sample_time_end_valve_car_tank=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
                
        case 2  %       2 -- valve_car_tank_hard_fault
                ws_sample_time_end_valve_car_tank=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 3    %       3 -- valve_minipump_in_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 4  %       4 -- valve_minipump_in_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 5%       5 -- valve_minipump_out_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 6  %       6 -- valve_minipump_out_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 7  %       7 -- valve_tank1_in_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 8  %       8 -- valve_tank1_in_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 9  %       9 -- valve_tank1_out_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 10 %       10 -- valve_tank1_out_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 11 %       11 -- valve_tank2_in_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 12 %       12 -- valve_tank2_in_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 13%       13 -- valve_tank2_out_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 14 %       14 -- valve_tank2_out_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 15%       15 -- valve_tank3_in_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 16 %       16 -- valve_tank3_in_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 17 %       17 -- valve_tank3_out_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 18 %       18 -- valve_tank3_out_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 19 %       19 -- valve_bigpump_in_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 20%       20 -- valve_bigpump_in_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 21 %       21 -- valve_bigpump_out_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 22%       22 -- valve_bigpump_out_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 23%       23 -- valve_general_tank_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 24%       24 -- valve_general_tank_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 25%       25 -- filter_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=soft+1;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 26%       26 -- filter_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=fault_time+time_const;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=hard+1.5;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=0;
                assignin('base', 'gain_coef', gain_coef);
        case 27%       27 -- minipump_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=0;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=1;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=2000*10;
                assignin('base', 'gain_coef', gain_coef);

        case 28%       28 -- minipump_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=0;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=1;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=0;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=4000*10;
                assignin('base', 'gain_coef', gain_coef);
        case 29%       29 -- bigpump_soft_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=0;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=1;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=2000*10;
                assignin('base', 'gain_coef', gain_coef);
        case 30%       30 -- bigpump_hard_fault
                ws_sample_time_end_valve_car_tank=0;
                assignin('base', 'ws_sample_time_end_valve_car_tank', ws_sample_time_end_valve_car_tank);
                ws_sample_time_end_valve_minipump_in=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_in', ws_sample_time_end_valve_minipump_in);
                ws_sample_time_end_valve_minipump_out=0;
                assignin('base', 'ws_sample_time_end_valve_minipump_out', ws_sample_time_end_valve_minipump_out);
                ws_sample_time_end_valve_cartank1_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_out', ws_sample_time_end_valve_cartank1_out);
                ws_sample_time_end_valve_cartank1_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank1_in', ws_sample_time_end_valve_cartank1_in);
                ws_sample_time_end_valve_cartank2_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_out', ws_sample_time_end_valve_cartank2_out);
                ws_sample_time_end_valve_cartank2_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank2_in', ws_sample_time_end_valve_cartank2_in);
                ws_sample_time_end_valve_cartank3_out=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_out', ws_sample_time_end_valve_cartank3_out);
                ws_sample_time_end_valve_cartank3_in=0;
                assignin('base', 'ws_sample_time_end_valve_cartank3_in', ws_sample_time_end_valve_cartank3_in);
                ws_sample_time_end_filter=0;
                assignin('base', 'ws_sample_time_end_filter', ws_sample_time_end_filter);
                ws_sample_time_end_valve_bigpump_in=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_in', ws_sample_time_end_valve_bigpump_in);
                ws_sample_time_end_valve_bigpump_out=0;
                assignin('base', 'ws_sample_time_end_valve_bigpump_out',  ws_sample_time_end_valve_bigpump_out);
                ws_sample_time_end_valve_general_tank=0;
                assignin('base', 'ws_sample_time_end_valve_general_tank',  ws_sample_time_end_valve_general_tank);
                amplitude=0;
                assignin('base', 'amplitude',  amplitude);
                minipump_const=0;
                assignin('base', 'minipump_const',  minipump_const);
                bigpump_const=1;
                assignin('base', 'bigpump_const',  bigpump_const);
                gain_coef=4000*10;
                assignin('base', 'gain_coef', gain_coef);
            
    end
    sim('FaultDataGeneratorNew')
    observed_data = ws_observed_data';
    
end